version: '3.3'

networks:
  monitoring:
    attachable: true

configs:
  prometheus_config_step_2:
    file: ./prometheus.yml

services:

  prometheus:
    image: 'prom/prometheus:v1.8.2'
    ports:
      - '9090:9090'
    networks:
      - monitoring
    command: >-
      -config.file=/etc/prometheus/prometheus.yml
      -storage.local.path=/prometheus
      -web.console.libraries=/etc/prometheus/console_libraries
      -web.console.templates=/etc/prometheus/consoles
    configs:
      - source: prometheus_config_step_2
        target: /etc/prometheus/prometheus.yml

  cadvisor:
    image: 'google/cadvisor:v0.26.1'
    networks:
      - monitoring
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock,readonly'
      - '/:/rootfs'
      - '/var/run:/var/run'
      - '/sys:/sys'
      - '/var/lib/docker/:/var/lib/docker'
    deploy:
      mode: global
