apiVersion: v1
kind: Service
metadata:
  labels:
    service: prometheus
  name: prometheus
spec:
  type: LoadBalancer
  ports:
  - name: "9090"
    port: 9090
    targetPort: 9090
  selector:
    service: prometheus
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    service: prometheus
  name: prometheus
spec:
  replicas: 1
  template:
    metadata:
      labels:
        service: prometheus
    spec:
      containers:
      - args:
        - -config.file=/etc/prometheus/prometheus.yml
        - -storage.local.path=/prometheus
        - -web.console.libraries=/etc/prometheus/console_libraries
        - -web.console.templates=/etc/prometheus/consoles
        image: prom/prometheus:v1.8.2
        name: prometheus
        volumeMounts:
        - mountPath: /etc/prometheus/prometheus.yml
          name: prom-config
        ports:
        - containerPort: 9090  
      volumes:
      - name: prom-config
        hostPath: 
          path: /prometheus_grafana/prometheus.yml
          type: File  
      restartPolicy: Always
