global:
  scrape_interval:     30s
  evaluation_interval: 30s

scrape_configs:
  - job_name: 'prometheus'
    dns_sd_configs:
    - names:
      - prometheus
      type: 'A'
      port: 9090

  - job_name: 'cadvisor'
    dns_sd_configs:
    - names:
      - cadvisor
      type: 'A'
      port: 8080

  - job_name: 'node-exporter'
    dns_sd_configs:
    - names:
      - node-exporter
      type: 'A'
      port: 9100

  - job_name: 'postgres'
    dns_sd_configs:
    - names:
      - postgres-e
      type: 'A'
      port: 9187

  - job_name: 'traefik'
    dns_sd_configs:
    - names:
      - traefik
      type: 'A'
      port: 8080

