global:
  scrape_interval:     30s
  evaluation_interval: 30s

scrape_configs:
  - job_name: 'prometheus'
    dns_sd_configs:
    - names:
      - prometheus.default.svc.cluster.local.
      type: 'A'
      port: 9090

  - job_name: 'cadvisor'
    dns_sd_configs:
    - names:
      - cadvisor.default.svc.cluster.local.
      type: 'A'
      port: 8080

  - job_name: 'node-exporter'
    dns_sd_configs:
    - names:
      - node-exporter.default.svc.cluster.local.
      type: 'A'
      port: 9100

  - job_name: 'postgres'
    dns_sd_configs:
      - names:
          - postgres-exporter.default.svc.cluster.local.
        type: 'A'
        port: 9187

  - job_name: 'traefik'
    dns_sd_configs:
      - names:
          - traefik.default.svc.cluster.local.
        type: 'A'
        port: 8080
