apiVersion: v1
kind: Service
metadata:
  labels:
    service: prometheus
  name: prometheus
spec:
  type: LoadBalancer
  ports:
  - name: "9090"
    port: 9090
    targetPort: 9090
  selector:
    service: prometheus
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    service: prometheus
  name: prometheus
spec:
  replicas: 1
  template:
    metadata:
      labels:
        service: prometheus
    spec:
      containers:
      - args:
        - -config.file=/etc/prometheus/prometheus.yml
        - -storage.local.path=/prometheus
        - -web.console.libraries=/etc/prometheus/console_libraries
        - -web.console.templates=/etc/prometheus/consoles
        image: prom/prometheus:v1.8.2
        name: prometheus
        volumeMounts:
        - mountPath: /etc/prometheus/prometheus.yml
          name: prom-config
        ports:
        - containerPort: 9090
      volumes:
      - name: prom-config
        hostPath:
          path: /prometheus_grafana/kubernetes/prometheus.yml
          type: File
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  labels:
    service: cadvisor
  name: cadvisor
spec:
  type: LoadBalancer
  ports:
  - name: "8080"
    port: 8080
    targetPort: 8080
  selector:
    service: cadvisor
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    service: cadvisor
  name: cadvisor
spec:
  replicas: 1
  template:
    metadata:
      labels:
        service: cadvisor
    spec:
      containers:
      - image: google/cadvisor:v0.26.1
        name: cadvisor
        volumeMounts:
        - mountPath: /var/run
          name: varrun
        - mountPath: /var/run/docker.sock
          name: varrundockersock
        - mountPath: /rootfs
          name: root
        - mountPath: /var/lib/docker
          name: varlibdocker
        - mountPath: /sys
          name: sysfs
        ports:
        - containerPort: 8080
      volumes:
      - name: varrun
        hostPath:
          path: /var/run
          type: Directory
      - name: varrundockersock
        hostPath:
          path: /var/run/docker.sock
          type: File
      - name: root
        hostPath:
          path: /
          type: Directory
      - name: varlibdocker
        hostPath:
          path: /var/lib/docker
          type: Directory
      - name: sysfs
        hostPath:
          path: /sys
          type: Directory
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  labels:
    service: node-exporter
  name: node-exporter
spec:
  type: LoadBalancer
  ports:
  - name: headless
    port: 55555
    targetPort: 0
  selector:
    service: node-exporter
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    service: node-exporter
  name: node-exporter
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        service: node-exporter
    spec:
      containers:
      - name: node-exporter
        image: basi/node-exporter
        command: ["/bin/node_exporter"]
        args:
        - --path.procfs "/host/proc"
        - --path.sysfs /host/sys
        - --collector.textfile.directory /etc/node-exporter/
        - --collector.filesystem.ignored-mount-points "^/(sys|proc|dev|host|etc)($|/)"
        volumeMounts:
        - mountPath: /host/proc
          name: hostproc
        - mountPath: /host/sys
          name: hostsys
        - mountPath: /rootfs
          name: rootfs
      restartPolicy: Always
      volumes:
      - name: hostproc
        hostPath:
          path: /proc
          type: Directory
      - name: hostsys
        hostPath:
          path: /sys
          type: Directory
      - name: rootfs
        hostPath:
          path: /
          type: Directory