apiVersion: v1
kind: Service
metadata:
  labels:
    service: prometheus
  name: prometheus
spec:
  type: LoadBalancer
  ports:
  - name: "9090"
    port: 9090
    targetPort: 9090
  selector:
    service: prometheus
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    service: prometheus
  name: prometheus
spec:
  replicas: 1
  template:
    metadata:
      labels:
        service: prometheus
    spec:
      containers:
      - args:
        - -config.file=/etc/prometheus/prometheus.yml
        - -storage.local.path=/prometheus
        - -web.console.libraries=/etc/prometheus/console_libraries
        - -web.console.templates=/etc/prometheus/consoles
        image: prom/prometheus:v1.8.2
        name: prometheus
        volumeMounts:
        - mountPath: /etc/prometheus/prometheus.yml
          name: prom-config
        ports:
        - containerPort: 9090
      volumes:
      - name: prom-config
        hostPath:
          path: /prometheus_grafana/kubernetes/prometheus.yml
          type: File
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  labels:
    service: cadvisor
  name: cadvisor
spec:
  type: LoadBalancer
  ports:
  - name: "8080"
    port: 8080
    targetPort: 8080
  selector:
    service: cadvisor
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    service: cadvisor
  name: cadvisor
spec:
  replicas: 1
  template:
    metadata:
      labels:
        service: cadvisor
    spec:
      containers:
      - image: google/cadvisor:v0.26.1
        name: cadvisor
        volumeMounts:
        - mountPath: /var/run
          name: varrun
        - mountPath: /var/run/docker.sock
          name: varrundockersock
        - mountPath: /
          name: root
        - mountPath: /var/lib/docker
          name: varlibdocker
        - mountPath: /sys
          name: sysfs
        ports:
        - containerPort: 8080
      volumes:
      - name: varrun
        source:
          hostDir:
            path: /var/run
      - name: varrundockersock
        source:
          hostDir:
            path: /var/run/docker.sock
      - name: root
        source:
          hostDir:
            path: /rootfs
      - name: varlibdocker
        source:
          hostDir:
            path: /var/lib/docker
      - name: sysfs
        source:
          hostDir:
            path: /sys
      restartPolicy: Always
