apiVersion: v1
kind: Service
metadata:
  labels:
    service: prometheus
  name: prometheus
spec:
  type: LoadBalancer
  ports:
  - name: "9090"
    port: 9090
    targetPort: 9090
  selector:
    service: prometheus
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    service: prometheus
  name: prometheus
spec:
  replicas: 1
  template:
    metadata:
      labels:
        service: prometheus
    spec:
      containers:
      - args:
        - -config.file=/etc/prometheus/prometheus.yml
        - -storage.local.path=/prometheus
        - -web.console.libraries=/etc/prometheus/console_libraries
        - -web.console.templates=/etc/prometheus/consoles
        image: prom/prometheus:v1.8.2
        name: prometheus
        volumeMounts:
        - mountPath: /etc/prometheus/prometheus.yml
          name: prom-config
        ports:
        - containerPort: 9090
          name: prometheus-scrape
      volumes:
      - name: prom-config
        hostPath:
          path: /prometheus_grafana/kubernetes/prometheus.yml
          type: File
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  labels:
    service: cadvisor
  name: cadvisor
spec:
  clusterIP: None
  ports:
  - name: "8080"
    port: 8080
    protocol: TCP
  selector:
    service: cadvisor
  type: ClusterIP
---
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  labels:
    service: cadvisor
  name: cadvisor
spec:
  template:
    metadata:
      name: cadvisor
      labels:
        service: cadvisor
    spec:
      containers:
      - image: google/cadvisor:v0.26.1
        name: cadvisor
        ports:
        - containerPort: 8080
          hostPort: 8080
          name: cadvisor-scrape
      hostNetwork: true
      hostPID: true
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: node-exporter
    name: node-exporter
  name: node-exporter
spec:
  clusterIP: None
  ports:
  - name: "9100"
    port: 9100
    protocol: TCP
  selector:
    app: node-exporter
  type: ClusterIP
---
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: node-exporter
spec:
  template:
    metadata:
      labels:
        app: node-exporter
      name: node-exporter
    spec:
      containers:
      - image: prom/node-exporter
        name: node-exporter
        ports:
        - containerPort: 9100
          hostPort: 9100
          name: node-exporter-scrape
      hostNetwork: true
      hostPID: true